# Generated by Django 5.1.6 on 2025-03-16 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('status', models.CharField(max_length=200)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='OK', max_length=200)),
                ('expiration_date', models.DateTimeField(null=True, verbose_name='expiration date')),
                ('registrar', models.CharField(max_length=200, null=True)),
                ('response_code', models.IntegerField(null=True)),
                ('response_time', models.FloatField(null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.domain', unique=True)),
            ],
        ),
    ]
