# Generated by Django 5.1.6 on 2025-03-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainstatus',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.domain'),
        ),
    ]
